"""Initial migration

Revision ID: 3b2a83640046
Revises: 
Create Date: 2026-05-28 10:50:17.182872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2a83640046'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sesi_ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_sesi', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesi_ujian_id'), 'sesi_ujian', ['id'], unique=False)
    op.create_index(op.f('ix_sesi_ujian_pin_sesi'), 'sesi_ujian', ['pin_sesi'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('peserta_ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sesi_id', sa.Integer(), nullable=True),
    sa.Column('agent_status', sa.String(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sesi_id'], ['sesi_ujian.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peserta_ujian_id'), 'peserta_ujian', ['id'], unique=False)
    op.create_table('log_anomali',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peserta_id', sa.Integer(), nullable=True),
    sa.Column('tipe_anomali', sa.String(), nullable=True),
    sa.Column('metadata_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['peserta_id'], ['peserta_ujian.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_anomali_id'), 'log_anomali', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_anomali_id'), table_name='log_anomali')
    op.drop_table('log_anomali')
    op.drop_index(op.f('ix_peserta_ujian_id'), table_name='peserta_ujian')
    op.drop_table('peserta_ujian')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sesi_ujian_pin_sesi'), table_name='sesi_ujian')
    op.drop_index(op.f('ix_sesi_ujian_id'), table_name='sesi_ujian')
    op.drop_table('sesi_ujian')
    # ### end Alembic commands ###
